### ISSUE TITLE
preprints 

### ISSUE THREAD

**Issue by alicia-cassidy** [dfo-osdt/osp#108]
Add category in the + creating a manuscript button for Preprints with definition 

Then after it is approved by manager, there could be a way to change the category from preprint to primary or secondary paper. Here, they could modify the answers to the questions if needed in the MRF and upload the new manuscript

Then there could be a series of questions for the author - 
- is there sensitive material in the manuscript (deemed by the author or by the manager when reviewing the preprint)
- has the results or interpretation of the results changed or been added to since the manager approval
- 
**if either of these boxes check yes, then the new MRF is sent again for manager approval, and can have some explanatory text as to why we are asking the questions

**Comment by vincentauger** [comment]
For preprint - would the ability to add a URL or DOI to the MRF be a good solution?

**Comment by vincentauger** [comment]
closing for now, hopefully we get more clarity with new publication policy.
