### ISSUE TITLE
keywords

### ISSUE THREAD

**Issue by alicia-cassidy** [dfo-osdt/osp#114]
Should we ask authors to add keywords (for tracking/stats purposes) - or AI to extract keywords from the manuscript based on a master list of keywords.

**Comment by vincentauger** [comment]
I think this is something we should bring forward at our next meeting with libraries. It would be nice to populate the system with their existing keywords on top of having the ability to add new ones?

**Comment by alicia-cassidy** [comment]
Yes good idea!
