### ISSUE TITLE
My reviews - section

### ISSUE THREAD

**Issue by alicia-cassidy** [dfo-osdt/osp#116]
Will the My Reviews section only be for managers?  It will be mis-leading when the portal is also used for the secondary papers review process since My Reviews sounds more like it should be for Peer Review and not for Management Review....

Should it be called My Management Reviews? That sounds a bit weird? (It is possible - although I guess unlikely, that a manager could also be a peer-reviewer)

**Comment by vincentauger** [comment]
The idea I had is that both management reviews and peer review would appear under "My Review" but we can discuss.

**Comment by alicia-cassidy** [comment]
Oh ok, I hadn't thought of that. yes, we can discuss further later :)
