### ISSUE TITLE
Traduction du OSP en français

### ISSUE THREAD

**Issue by alicia-cassidy** [dfo-osdt/osp#142]
!
![Capture5](https://github.com/dfo-osdt/osp/assets/130665763/8e28e6c4-a2bf-4905-a51d-9599c4ae7a0b)

Dans la version PDF, le MRF en francais s'appelle le Formulaire de Registre des Manuscrits - mais on peut dire enregistrement, faudra just choisir.  

Aussi dans la section Dossier Manuscrit, le premier onglet (Former) est-ce que c'est sensé être Formulaire?

**Comment by vincentauger** [comment]
Encore une fois, traduction automatique. Je vais le changer :)
