### ISSUE TITLE
ASDF

### ISSUE THREAD

**Issue by alicia-cassidy** [dfo-osdt/osp#143]
![Capture6](https://github.com/dfo-osdt/osp/assets/130665763/24610425-5801-4978-bb70-5d8e41b534a7)

What does ASDF mean? It's there in the French and English versions

**Comment by vincentauger** [comment]
That’s the title of the manuscript .. would make more sense with a real title, but we could make it more clear?

**Comment by vincentauger** [comment]
Closing follow discussion with Alicia.
