### ISSUE TITLE
Put tags on user profiles, that just allows them certain access - we can talk of this in person

### ISSUE THREAD

**Issue by alicia-cassidy** [dfo-osdt/osp#157]
Each user should be labeled as : applicant, author, division manager, RDS, DG, reviewer (for peer review only), editor.  Users can have more than one label, but this would ensure that people only have access to options and things they are supposed to see.

E.g. if authors mistakenly send the MRF to their section head for approval because they are unaware and did not read the instructions, then the section head who is acting and also unaware approves a publication and then no one knows about it....

OR authors that don't know what's what and think a management review is a peer review and sends it to their friends for peer review and these randos accept the management review...  This would probably happen, people won't read the instructions carefully

Authors/applicants (and potentially editors) can only send their publication for management review to a division manager and the division manager can then forward this to the RDS or DG, and the RDS could send it to the DG. 

Now, anyone can be a division manager, which is ok for beta testing, but we should change before the soft launch!

**Comment by alicia-cassidy** [comment]
There could also be a tag for general user - if someone wants to search for pubs or mrfs but doesn't have a specific role in the process (e.g. section head, or technician..._)

**Comment by vincentauger** [comment]
Add "roles and abilities" section to the user profile page.
