### ISSUE TITLE
When managers go over the 10 days to review

### ISSUE THREAD

**Issue by alicia-cassidy** [dfo-osdt/osp#163]
![Capture](https://github.com/dfo-osdt/osp/assets/130665763/cff4284d-3d4b-4c11-a191-2a848df63045)

When an author submits for review the 'mark as submitted' and 'accepted for publication' buttons are blocked. Do these unblock automatically after 10 days when the manager fails to review?

**Comment by vincentauger** [comment]
Currently, they stay closed. We now calculate the 10 days so it would be possible to implement if this is something we want.

![image](https://github.com/user-attachments/assets/d5b80d6f-e4b3-4777-ad4e-9272b21d54a8)
