### ISSUE TITLE
When you save a draft manuscript it is not counted in My Manuscripts

### ISSUE THREAD

**Issue by alicia-cassidy** [dfo-osdt/osp#214]
Delphine and Simon have pointed this out, that when they saved the draft manuscript, left and went back to my manuscripts it said 0 manuscripts so they were under the impression that it had not saved.

Minor issue, but maybe we can count the draft manuscripts?

**Comment by vincentauger** [comment]
The idea was that they are "in progress" once submitted but if two people pointed it out - we should likely count "draft" as "in progress"

**Comment by alicia-cassidy** [comment]
I guess, just because they were concerned about it :)
