### ISSUE TITLE
Adding ability to management reviewers to forward to comms

### ISSUE THREAD

**Issue by alicia-cassidy** [dfo-osdt/osp#220]
From Simon (and also something already on our list of things to do): add the ability for the management reviewer to forward an MRF to communications

**Comment by vincentauger** [comment]
By clicking on "yes" to potential public interest, communication will instantly have access (within the portal) to the MRF and be warned throughout the publishing journey. Is forwarding the message then still a feature we want? Additionally, they could add someone else as an observer.
