### ISSUE TITLE
Adding section heads as observers when an MRF is submitted

### ISSUE THREAD

**Issue by alicia-cassidy** [dfo-osdt/osp#222]
I think if we just add section heads as observers it is good enough (don't need to be inlcuded in the management review, even though some have provided feedback in this regard) since they can talk with the authors directly if there is an issue, and guide them in telling them if something would be of public interest.  We could add some 'guidance' text in the MRF when adding observers to talk to their section heads about the contents of the MRF before submitting it...

**Comment by vincentauger** [comment]
This feature will require the following:

- [ ] Create MRF observer many-to-many table
- [ ] Invite observers if they are not part of the portal
- [ ] Modify model policies and filters to display observed manuscripts when these users login
- [ ] Ensure observers are kept up to date until publication is marked as published.

**Comment by vincentauger** [comment]
Also mentioned as good idea from Pacific Admin group to keep an eye on MRF that have to be reviewed by Division Managers

**Comment by alicia-cassidy** [comment]
> Also mentioned as good idea from Pacific Admin group to keep an eye on MRF that have to be reviewed by Division Managers

Yes, the only thing is that the applicant or author will need to know who that admin is. Maybe that is not a problem
