### ISSUE TITLE
Creating new authors with new affiliations

### ISSUE THREAD

**Issue by alicia-cassidy** [dfo-osdt/osp#241]
From Cindy:

When creating a new author and adding his affiliation - it is a bit time consuming for the applicant to add and find the organization name and abbreviations in English and in French. They should be able to enter just the organization name in the language of their choice- and let the portal admins deal with completing the rest (Other language name and abbreviations of both languages). It could be time consuming when you have multiple authors from different places (which is often the case with external publications)

I'm also thinking when adding a new author we could say optional for ORCID ID, because that is also extra work for the applicant that they wouldn't normally have to do. I think once that new author signs up, then they could be prompted to fill in the rest of their personal information (like ORCID ID...)

**Comment by vincentauger** [comment]
Adoption of ROR in #298 and clarification of optional ORCID field in author creation should resolve these.
