### ISSUE TITLE
Specify in applicant email how to see management review comments

### ISSUE THREAD

**Issue by alicia-cassidy** [dfo-osdt/osp#244]
Marie-Claire

Could modify text in email to applicant on how to find the managers comment (go to review tab)

**Comment by vincentauger** [comment]
@alicia-cassidy - Another option here is to point directly from that tab on the "review completed" email?

**Comment by alicia-cassidy** [comment]
vincent

> @alicia-cassidy - Another option here is to point directly from that tab on the "review completed" email?

That works!
