### ISSUE TITLE
Add info in author profiles

### ISSUE THREAD

**Issue by alicia-cassidy** [dfo-osdt/osp#331]
Section
Division

Then could search by section or division just for the present, but not useful for past searches (I think that is fine). It would be up to the authors to keep their profiles up to date, there could be reminders to ask randomly if their info is still correct.

**Comment by vincentauger** [comment]
@alicia-cassidy  Do you still want to do this?

**Comment by vincentauger** [comment]
Following discussion with @alicia-cassidy, we'll add regions and sectors to the author profiles as a choice as the more detailed section and division are fluid.

**Comment by vincentauger** [comment]
Closing until we have a clear need as per discussion with @alicia-cassidy
