### ISSUE TITLE
Ability to add various file attachements to publications

### ISSUE THREAD

**Issue by vincentauger** [dfo-osdt/osp#475]
Some files with the following types to start: 

- MRF (for ones created outside the portal)
- Licensing agreements (with editors)
- ?

**Comment by alicia-cassidy** [comment]
- Plain Language summaries (in both official language) if MRF not done through the portal
For DFO publication submissions to the editor:
 - Manuscript that is ready for peer review (if not the same as the one for management review) sometimes the author makes small changes and that is ok
-
