### ISSUE TITLE
Change Create Manuscript to Create Manuscript Record Form

### ISSUE THREAD

**Issue by alicia-cassidy** [dfo-osdt/osp#548]
![image](https://github.com/dfo-osdt/osp/assets/130665763/808c8e47-be5b-445d-af19-dbcd03097431)

Change 'Create Manuscript' button to 'Create Manuscript Record Form' for clarity

**Comment by vincentauger** [comment]
Because of the available context on this page and the length of the french translation we've currently went with "Create Entry" which generalizes the action and removes the potential confusion with the concept of creating a manuscript instead of a manuscript record form.
