### ISSUE TITLE
Change text in box: Create a new manuscript record

### ISSUE THREAD

**Issue by alicia-cassidy** [dfo-osdt/osp#551]
![image](https://github.com/dfo-osdt/osp/assets/130665763/9afc792c-63d7-4cca-8449-fa8f1c2bf00e)

Change text to:

Create a New Manuscript Record Form

A manuscript to be published by a third party
Scientific or technical document to be published in a third party journal, special issue, book chapter, book or conference proceeding

A manuscript to be published by DFO
Scientific or technical document to be published in a DFO Science Series

**Comment by vincentauger** [comment]
![image](https://github.com/dfo-osdt/osp/assets/19717710/dc558209-14db-4e09-b133-05ddbb87966e)
