### ISSUE TITLE
Add option to return form to author - instead of withheld it could be on hold first

### ISSUE THREAD

**Issue by alicia-cassidy** [dfo-osdt/osp#570]
The back and forth for management review - between authors and managers. This would stop the clock. Not necessarily have withheld status, but more like 'on hold" (more like the rescope option for client requests in the CSAS dmapps).

**Comment by vincentauger** [comment]
The following interaction would all occur within the management review module. Interaction occurs within the management review flow and applicant notified if new status "flagged" is used by division manager. If the applicant doesn't want to address it, they can just resubmit right away back to the DM or the RDS.

```mermaid
sequenceDiagram
 Applicant->>DM: Submits for Management Review (Management has 10 days)
 DM->>Applicant: Marked as Flagged (stops 10-day commitment)
 Note over Applicant: Can now edit MRF again and/or upload revised manuscript.
 Applicant->>DM: Addresses concern (Management has 10 days)
 Note over DM: Approves and completes review.
```

**Comment by alicia-cassidy** [comment]
Perfect!
