### ISSUE TITLE
For Management Review - Make downloading the manuscript easier and more obvious

### ISSUE THREAD

**Issue by alicia-cassidy** [dfo-osdt/osp#571]
![image](https://github.com/dfo-osdt/osp/assets/130665763/e5335d4b-35db-4dbc-85ea-3a874e54eddc)

When conducting a management review, it is not very obvious where and how to download the manuscript to review it. Would it be too complicated to enhance the look and move the download PDF to the top of the page when you are viewing the MRF as a manager? Or can we attach the PDF to the Review tab?

**Comment by vincentauger** [comment]
We can do either or both. There's no harm in having at the top of the page for everyone as well really. Ideally, it would be the first step and we could scan the pdf to extract most of the MRF information to help but that does require further consideration.

**Comment by alicia-cassidy** [comment]
Putting it at the top of the page is good for now :) And yes, that would be cool to be able to self populate. Can keep it in mind for our later!
