### ISSUE TITLE
Should 'journal' be called "journal or series"?

### ISSUE THREAD

**Issue by alicia-cassidy** [dfo-osdt/osp#863]
![image](https://github.com/user-attachments/assets/415aa719-0faf-4219-af7d-a774d0c2f4ea)

Just because the secondary reports are called series. 

Also we need to add one called "Other DFO Science Report" Since we want to add the one-offs that are not part of any series.

**Comment by vincentauger** [comment]
Ok, will change to Journal/Series. For other one off, will they have an issn? isbn?

**Comment by alicia-cassidy** [comment]
For other one off, will they have an issn? isbn?

  *   Yes, but sometimes they have one or the other, or sometimes both, the ISSN if they have one is usually different form one report to the next (unless its an un-official mini series)
