### ISSUE TITLE
File size allowed is too small for accepted publications

### ISSUE THREAD

**Issue by alicia-cassidy** [dfo-osdt/osp#887]
trying to add a file to accepted publications for this entry https://osp-pso.ent.dfo-mpo.ca/#/publication/14
and this publication, but it says the file is too big to add. https://waves-vagues.dfo-mpo.gc.ca/library-bibliotheque/[41263625.pdf](https://waves-vagues.dfo-mpo.gc.ca/library-bibliotheque/41263625.pdf)

**Comment by vincentauger** [comment]
Currently, set at 200MB but we should discuss a standard. Such large PDFs just bog down the viewers so if they can be optimized, we should look at that as well.
